# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(816, 550)
        self.verticalLayoutWidget = QtWidgets.QWidget(Home)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 20, 551, 482))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cmb_destinasi = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cmb_destinasi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cmb_destinasi.setObjectName("cmb_destinasi")
        self.verticalLayout.addWidget(self.cmb_destinasi)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.calendar = QtWidgets.QCalendarWidget(self.verticalLayoutWidget)
        self.calendar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calendar.setObjectName("calendar")
        self.verticalLayout.addWidget(self.calendar)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.sb_pengunjung = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sb_pengunjung.setObjectName("sb_pengunjung")
        self.verticalLayout.addWidget(self.sb_pengunjung)
        self.label_harga = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_harga.setObjectName("label_harga")
        self.verticalLayout.addWidget(self.label_harga)
        self.btn_beli = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_beli.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_beli.setObjectName("btn_beli")
        self.verticalLayout.addWidget(self.btn_beli)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Form"))
        self.label.setText(_translate("Home", "Pilih Destinasi Wisata:"))
        self.label_2.setText(_translate("Home", "Pilih Tanggal Kunjungan"))
        self.label_3.setText(_translate("Home", "Jumlah Pengunjung:"))
        self.label_harga.setText(_translate("Home", "Total Harga: 0"))
        self.btn_beli.setText(_translate("Home", "Beli Tiket"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QWidget()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
