# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(816, 550)
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(0, 30, 821, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Login)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 130, 491, 332))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.field_username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.field_username.setMinimumSize(QtCore.QSize(0, 50))
        self.field_username.setObjectName("field_username")
        self.verticalLayout.addWidget(self.field_username)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.field_pw = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.field_pw.setMinimumSize(QtCore.QSize(0, 50))
        self.field_pw.setObjectName("field_pw")
        self.verticalLayout.addWidget(self.field_pw)
        self.btn_to_register = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_to_register.setFlat(True)
        self.btn_to_register.setObjectName("btn_to_register")
        self.verticalLayout.addWidget(self.btn_to_register)
        self.btn_login = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_login.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login.setAutoDefault(False)
        self.btn_login.setDefault(False)
        self.btn_login.setFlat(False)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout.addWidget(self.btn_login)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(5, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.label.setText(_translate("Login", "Reservasi Paket Wisata"))
        self.label_2.setText(_translate("Login", "Username"))
        self.label_3.setText(_translate("Login", "Password"))
        self.btn_to_register.setText(_translate("Login", "Belum memiliki akun? Daftar disini"))
        self.btn_login.setText(_translate("Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
