# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(816, 550)
        self.label = QtWidgets.QLabel(Register)
        self.label.setGeometry(QtCore.QRect(0, 10, 821, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Register)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 90, 491, 398))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.field_email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.field_email.setMinimumSize(QtCore.QSize(0, 50))
        self.field_email.setObjectName("field_email")
        self.verticalLayout.addWidget(self.field_email)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.field_username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.field_username.setMinimumSize(QtCore.QSize(0, 50))
        self.field_username.setObjectName("field_username")
        self.verticalLayout.addWidget(self.field_username)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.field_pw = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.field_pw.setMinimumSize(QtCore.QSize(0, 50))
        self.field_pw.setObjectName("field_pw")
        self.verticalLayout.addWidget(self.field_pw)
        self.btn_to_login = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_to_login.setFlat(True)
        self.btn_to_login.setObjectName("btn_to_login")
        self.verticalLayout.addWidget(self.btn_to_login)
        self.btn_register = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_register.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_register.setAutoDefault(False)
        self.btn_register.setDefault(False)
        self.btn_register.setFlat(False)
        self.btn_register.setObjectName("btn_register")
        self.verticalLayout.addWidget(self.btn_register)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(7, 1)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Form"))
        self.label.setText(_translate("Register", "Daftar Akun"))
        self.label_4.setText(_translate("Register", "Email"))
        self.label_2.setText(_translate("Register", "Username"))
        self.label_3.setText(_translate("Register", "Password"))
        self.btn_to_login.setText(_translate("Register", "Sudah memiliki akun? Login disini"))
        self.btn_register.setText(_translate("Register", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Register = QtWidgets.QWidget()
    ui = Ui_Register()
    ui.setupUi(Register)
    Register.show()
    sys.exit(app.exec_())
