# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ticket.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ticket(object):
    def setupUi(self, Ticket):
        Ticket.setObjectName("Ticket")
        Ticket.resize(816, 550)
        self.label = QtWidgets.QLabel(Ticket)
        self.label.setGeometry(QtCore.QRect(260, 40, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(Ticket)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 110, 561, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_tujuan = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_tujuan.setObjectName("label_tujuan")
        self.verticalLayout.addWidget(self.label_tujuan)
        self.label_tanggal = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_tanggal.setObjectName("label_tanggal")
        self.verticalLayout.addWidget(self.label_tanggal)
        self.label_pengunjung = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_pengunjung.setObjectName("label_pengunjung")
        self.verticalLayout.addWidget(self.label_pengunjung)
        self.label_harga = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_harga.setObjectName("label_harga")
        self.verticalLayout.addWidget(self.label_harga)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_kembali = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_kembali.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_kembali.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_kembali.setObjectName("btn_kembali")
        self.verticalLayout.addWidget(self.btn_kembali)

        self.retranslateUi(Ticket)
        QtCore.QMetaObject.connectSlotsByName(Ticket)

    def retranslateUi(self, Ticket):
        _translate = QtCore.QCoreApplication.translate
        Ticket.setWindowTitle(_translate("Ticket", "Form"))
        self.label.setText(_translate("Ticket", "Tiket Berhasil Dipesan!"))
        self.label_tujuan.setText(_translate("Ticket", "Tujuan: "))
        self.label_tanggal.setText(_translate("Ticket", "Hari/Tanggal:"))
        self.label_pengunjung.setText(_translate("Ticket", "Jumlah Pengunjung: "))
        self.label_harga.setText(_translate("Ticket", "Total Harga:"))
        self.btn_kembali.setText(_translate("Ticket", "Kembali ke menu awal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ticket = QtWidgets.QWidget()
    ui = Ui_Ticket()
    ui.setupUi(Ticket)
    Ticket.show()
    sys.exit(app.exec_())
